<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Guard;

/** @var \Zend\Form\FormInterface $form */
$form = $this->form;
?>
<h1><?= $this->translate('403 Forbidden'); ?></h1>

<div class="row">
    <!-- Simple login form -->
    <?= $this->form()->openTag($form); ?>
    <div class="panel panel-body col-md-3">

        <div class="form-group">
            <?= $this->formElement($form->get('username')->setAttributes([
                'class' => 'form-control',
                'placeholder' => $this->translate('Username'),
            ])); ?>
        </div>

        <div class="form-group">
            <?= $this->formElement($form->get('password')->setAttributes([
                'class' => 'form-control',
                'placeholder' => $this->translate('Password'),
            ])); ?>
        </div>

        <div class="form-group">
            <?= $this->formElement($form->get('redirect')); ?>

            <button type="submit" class="btn btn-primary">
                <?= $this->translate('Sign in'); ?> <i class="icon-circle-right2 position-right"></i>
            </button>

            <a href="#"><?= $this->translate('Forgot password?'); ?></a>
        </div>

    </div>
    <?= $this->form()->closeTag($form); ?>
    <!-- /simple login form -->
</div>
